# Generated by Django 3.1.4 on 2023-10-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='date',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(related_name='units', to='attendance.Student')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.unit'),
            preserve_default=False,
        ),
    ]
